hwdec=auto
hwdec-codecs=all
profile=high-quality
sub-auto=fuzzy
sub-font="Noto Sans CJK HK"
sub-font-size=50
keep-open=yes
save-position-on-quit=yes
screenshot-template="%F-%tY-%tm-%td_%tH-%tM-%tS"
screenshot-directory="~/Pictures/Screenshots/"
screenshot-format=png
